Calle: Calle
Avenida: Avenida
Paseo: Paseo
Plaza: Plaza
Acceso: Acceso
Arroyo: Arroyo
Autopista: Autopista
Autovía: Autovía
Bulevar: Bulevar
Callejón: Callejón
Camino: Camino
Carrera: Carrera
Carretera: Carretera
Cañada: Cañada
Colonia: Colonia
Constanilla: Constanilla
Cuesta: Cuesta
Galería: Galería
Glorieta: Glorieta
Parque: Parque
Pasadizo: Pasadizo
Pasaje: Pasaje
Pista: Pista
Plazuela: Plazuela
Puente: Puente
Ronda: Ronda
Travesía: Travesía